export const SOCIAL_LINKS = {
  whatsappChannel: {
    id: 'whatsapp-channel',
    title: 'Official WhatsApp Channel',
    subtitle: 'Daily MCQs, Announcements & Key Alerts',
    url: 'https://whatsapp.com/channel/0029Vb8KYZK9RZAUyyUEIf1C',
    badge: '📢 Official Channel',
    actionText: 'Follow Channel',
    iconType: 'channel',
    color: '#25D366',
    primary: true,
  },
  whatsappUpdatesGroup: {
    id: 'whatsapp-updates',
    title: 'MDCAT Updates Group',
    subtitle: 'Official Date Sheets, Syllabus & Tests',
    url: 'https://chat.whatsapp.com/FB2UYfYe4upEo1oSx8KXxd',
    badge: '🔔 Updates Group',
    actionText: 'Join Updates Group',
    iconType: 'updates',
    color: '#128C7E',
    primary: true,
  },
  whatsappDiscussionGroup: {
    id: 'whatsapp-discussion',
    title: 'Student Discussion Group',
    subtitle: 'Peer-to-Peer MCQ Discussions & Doubt Solving',
    url: 'https://chat.whatsapp.com/KR48IavmjK4BPC5HoX65mA',
    badge: '💬 Student Discussion',
    actionText: 'Join Discussion Group',
    iconType: 'discussion',
    color: '#075E54',
    primary: true,
  },
  whatsappSupport: {
    id: 'whatsapp-support',
    title: 'WhatsApp Direct Support',
    subtitle: 'Chat with Team: 0307-4172603',
    url: 'https://wa.me/923074172603?text=Hello%20MDCAT%20LMS%20Support',
    badge: '📞 WhatsApp Help',
    actionText: 'Message on WhatsApp',
    iconType: 'support',
    color: '#25D366',
    phone: '03074172603',
  },
  facebook: {
    id: 'facebook',
    title: 'Facebook Page',
    subtitle: 'Official Updates & Community Posts',
    url: 'https://www.facebook.com/share/1GEujVrgrf/',
    badge: 'Follow on Facebook',
    actionText: 'Visit Facebook',
    iconType: 'facebook',
    color: '#1877F2',
  },
  instagram: {
    id: 'instagram',
    title: 'Instagram Profile',
    subtitle: '@acemdcatofficial · Reels & Tips',
    url: 'https://www.instagram.com/acemdcatofficial?utm_source=qr&igsh=MWd5OTBtNm51eG5xdw==',
    badge: 'Follow on Instagram',
    actionText: 'Visit Instagram',
    iconType: 'instagram',
    color: '#E4405F',
  },
}

export const SOCIAL_COMMUNITY_LIST = [
  SOCIAL_LINKS.whatsappChannel,
  SOCIAL_LINKS.whatsappUpdatesGroup,
  SOCIAL_LINKS.whatsappDiscussionGroup,
  SOCIAL_LINKS.whatsappSupport,
  SOCIAL_LINKS.instagram,
  SOCIAL_LINKS.facebook,
]
